### ISSUE TITLE
Take age, phone number as input during one time Login.

### ISSUE THREAD

**Issue by saptarshiweb** [DSCKGEC/Health-Tracker-App#1]
In the Login Page make the necessary changes, add the required textfields and controllers.

**Comment by samitkapoor** [comment]
@saptarshiweb May I work on this issue?

**Comment by saptarshiweb** [comment]
@samitkapoor Hello ,nice to see your interest in contributing to this project. The contributing phase starts from 26th , please register yourself on the official website https://dscksoc.herokuapp.com/ and follow the further details.

**Comment by harshraj305** [comment]
@saptarshiweb  Hey, I am new to open-source. I would like to contribute on this project &
I have made the requirements of the LoginPage.
Can you assign this to me?
