### ISSUE TITLE
Create Walk, Sleep, Heart Rate, Water Consumed fields in the Sqlite Database

### ISSUE THREAD

**Issue by saptarshiweb** [DSCKGEC/Health-Tracker-App#4]
Changes needed to be made in both the files under the folder controller.

**Comment by Ohior** [comment]
I will like to work on this issue #4. But I have create a new database

**Comment by saptarshiweb** [comment]
Hello @Ohior , welcome to Ksoc. Can you pls share your brief approach to the problem on the discord channel ?

**Comment by Ohior** [comment]
> Hello @Ohior , welcome to Ksoc. Can you pls share your brief approach to the problem on the discord channel ?

I am not on the discord channel, can you add me.
You already have 2 database and I do not want to alter them. I wanted to create a new database with sqflite and a data class to help in getting and putting data into the database.
I have worked with sqflite before so I think I can do it.

**Comment by saptarshiweb** [comment]
Hello @Ohior, you can start working on the issue. I am assigning you.

**Comment by saptarshiweb** [comment]
@Ohior Join the Discord Channel here https://discord.gg/y29dVXph and ping me up on the health tracker channel .
